jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(e,a,c,b,d){return jQuery.easing[jQuery.easing.def](e,a,c,b,d)},easeInQuad:function(e,a,c,b,d){return b*(a/=d)*a+c},easeOutQuad:function(e,a,c,b,d){return-b*(a/=d)*(a-2)+c},easeInOutQuad:function(e,a,c,b,d){return(a/=d/2)<1?b/2*a*a+c:-b/2*(--a*(a-2)-1)+c},easeInCubic:function(e,a,c,b,d){return b*(a/=d)*a*a+c},easeOutCubic:function(e,a,c,b,d){return b*((a=a/d-1)*a*a+1)+c},easeInOutCubic:function(e,a,c,b,d){return(a/=d/2)<1?b/2*a*a*a+c:b/
2*((a-=2)*a*a+2)+c},easeInQuart:function(e,a,c,b,d){return b*(a/=d)*a*a*a+c},easeOutQuart:function(e,a,c,b,d){return-b*((a=a/d-1)*a*a*a-1)+c},easeInOutQuart:function(e,a,c,b,d){return(a/=d/2)<1?b/2*a*a*a*a+c:-b/2*((a-=2)*a*a*a-2)+c},easeInQuint:function(e,a,c,b,d){return b*(a/=d)*a*a*a*a+c},easeOutQuint:function(e,a,c,b,d){return b*((a=a/d-1)*a*a*a*a+1)+c},easeInOutQuint:function(e,a,c,b,d){return(a/=d/2)<1?b/2*a*a*a*a*a+c:b/2*((a-=2)*a*a*a*a+2)+c},easeInSine:function(e,a,c,b,d){return-b*Math.cos(a/
d*(Math.PI/2))+b+c},easeOutSine:function(e,a,c,b,d){return b*Math.sin(a/d*(Math.PI/2))+c},easeInOutSine:function(e,a,c,b,d){return-b/2*(Math.cos(Math.PI*a/d)-1)+c},easeInExpo:function(e,a,c,b,d){return a==0?c:b*Math.pow(2,10*(a/d-1))+c},easeOutExpo:function(e,a,c,b,d){return a==d?c+b:b*(-Math.pow(2,-10*a/d)+1)+c},easeInOutExpo:function(e,a,c,b,d){return a==0?c:a==d?c+b:(a/=d/2)<1?b/2*Math.pow(2,10*(a-1))+c:b/2*(-Math.pow(2,-10*--a)+2)+c},easeInCirc:function(e,a,c,b,d){return-b*(Math.sqrt(1-(a/=d)*
a)-1)+c},easeOutCirc:function(e,a,c,b,d){return b*Math.sqrt(1-(a=a/d-1)*a)+c},easeInOutCirc:function(e,a,c,b,d){return(a/=d/2)<1?-b/2*(Math.sqrt(1-a*a)-1)+c:b/2*(Math.sqrt(1-(a-=2)*a)+1)+c},easeInElastic:function(e,a,c,b,d){var e=1.70158,f=0,g=b;if(a==0)return c;if((a/=d)==1)return c+b;f||(f=d*0.3);g<Math.abs(b)?(g=b,e=f/4):e=f/(2*Math.PI)*Math.asin(b/g);return-(g*Math.pow(2,10*(a-=1))*Math.sin((a*d-e)*2*Math.PI/f))+c},easeOutElastic:function(e,a,c,b,d){var e=1.70158,f=0,g=b;if(a==0)return c;if((a/=
d)==1)return c+b;f||(f=d*0.3);g<Math.abs(b)?(g=b,e=f/4):e=f/(2*Math.PI)*Math.asin(b/g);return g*Math.pow(2,-10*a)*Math.sin((a*d-e)*2*Math.PI/f)+b+c},easeInOutElastic:function(e,a,c,b,d){var e=1.70158,f=0,g=b;if(a==0)return c;if((a/=d/2)==2)return c+b;f||(f=d*0.3*1.5);g<Math.abs(b)?(g=b,e=f/4):e=f/(2*Math.PI)*Math.asin(b/g);return a<1?-0.5*g*Math.pow(2,10*(a-=1))*Math.sin((a*d-e)*2*Math.PI/f)+c:g*Math.pow(2,-10*(a-=1))*Math.sin((a*d-e)*2*Math.PI/f)*0.5+b+c},easeInBack:function(e,a,c,b,d,f){f==void 0&&
(f=1.70158);return b*(a/=d)*a*((f+1)*a-f)+c},easeOutBack:function(e,a,c,b,d,f){f==void 0&&(f=1.70158);return b*((a=a/d-1)*a*((f+1)*a+f)+1)+c},easeInOutBack:function(e,a,c,b,d,f){f==void 0&&(f=1.70158);return(a/=d/2)<1?b/2*a*a*(((f*=1.525)+1)*a-f)+c:b/2*((a-=2)*a*(((f*=1.525)+1)*a+f)+2)+c},easeInBounce:function(e,a,c,b,d){return b-jQuery.easing.easeOutBounce(e,d-a,0,b,d)+c},easeOutBounce:function(e,a,c,b,d){return(a/=d)<1/2.75?b*7.5625*a*a+c:a<2/2.75?b*(7.5625*(a-=1.5/2.75)*a+0.75)+c:a<2.5/2.75?b*
(7.5625*(a-=2.25/2.75)*a+0.9375)+c:b*(7.5625*(a-=2.625/2.75)*a+0.984375)+c},easeInOutBounce:function(e,a,c,b,d){return a<d/2?jQuery.easing.easeInBounce(e,a*2,0,b,d)*0.5+c:jQuery.easing.easeOutBounce(e,a*2-d,0,b,d)*0.5+b*0.5+c}});var page1,page2,page3,page4,page0,pageN1,pageWidth,num=1,ajaxed=!1,nopage=!1,pageIndex=0,flipTime=500;
function pageLayout(){pageWidth=$(window).width()>=1280&&$(window).height()>=799?500:400;page1=$(".pagecontent:eq("+pageIndex+")");page1.addClass("page1").css("zIndex",1);page2=$(".pagecontent:eq("+parseInt(pageIndex+1)+")");page2.addClass("page2").css({left:pageWidth,zIndex:3,paddingRight:0,width:pageWidth});$(".page1 .pagenum").text(pageIndex+1);$(".page2 .pagenum").text(pageIndex+2);if(nopage!=!0&&$(".pagecontent").length<parseInt(pageIndex+6)&&ajaxed!=!0){num=Math.floor(pageIndex/4)+2;now=pageIndex;
var e=$("#catname").text();$.ajax({url:"?action=Ajax_post&"+e+"&page="+num,dataType:"html",contentType:"application/json; charset=utf-8",cache:!0,beforeSend:function(){ajaxed=!0},success:function(a){a.length>1?($("#mybook").append(a),now!=pageIndex&&(page3=$(".pagecontent:eq("+parseInt(pageIndex+2)+")"),page3.addClass("page3").css({left:pageWidth*2,zIndex:4,width:0,marginLeft:0,paddingLeft:0}),page4=$(".pagecontent:eq("+parseInt(pageIndex+3)+")"),page4.addClass("page4").css({left:pageWidth,zIndex:2}),
$("#next_page_button").show(0)),reload()):nopage=!0;ajaxed=!1},error:function(a){console.log(a);ajaxed=!1}})}$(".pagecontent").length>parseInt(pageIndex+2)?(page3=$(".pagecontent:eq("+parseInt(pageIndex+2)+")"),page3.addClass("page3").css({left:pageWidth*2,zIndex:4,width:0,marginLeft:0,paddingLeft:0}),page4=$(".pagecontent:eq("+parseInt(pageIndex+3)+")"),page4.addClass("page4").css({left:pageWidth,zIndex:2}),setTimeout(function(){$("#next_page_button").show(0)},500)):$("#next_page_button").hide(0);
pageIndex>1&&(page0=$(".pagecontent:eq("+parseInt(pageIndex-1)+")"),page0.addClass("page0").css({left:0,zIndex:0}),pageN1=$(".pagecontent:eq("+parseInt(pageIndex-2)+")"),pageN1.addClass("pageN1").css({left:0,zIndex:0}))}
function previousPage(){page0.css("zIndex",6).css("paddingRight",0);page0.children("div:first").css("marginLeft",-1*pageWidth);pageN1.css("zIndex",5).css("width",0);page0.children("div:first").animate({marginLeft:0},flipTime-100);page0.animate({left:pageWidth,width:pageWidth,paddingRight:30},{duration:flipTime,specialEasing:{left:"easeInOutQuad",width:"easeInOutQuad",paddingRight:"linear"}});pageN1.animate({width:pageWidth},flipTime,"easeInOutQuad",function(){page1.removeClass("page1");page2.removeClass("page2");
page3.removeClass("page3");page4.removeClass("page4");page0.removeClass("page0");pageN1.removeClass("pageN1");pageIndex-=2;pageLayout();$(this).dequeue()})}
function nextPage(){page3.animate({left:0,width:pageWidth},{duration:flipTime},{easing:"easeInOutQuad"});page2.animate({width:0},flipTime/2,"easeInOutQuad",function(){page1.removeClass("page1");page2.removeClass("page2");page3.removeClass("page3");page4.removeClass("page4");pageIndex>1&&(page0.removeClass("page0"),pageN1.removeClass("pageN1"));pageIndex+=2;pageLayout();$(this).dequeue()})}function next_page_button_click(){nextPage();$("#prev_page_button:hidden").fadeIn(300)}
function prev_page_button_click(){previousPage();pageIndex==2?$("#prev_page_button").fadeOut(0):setTimeout(function(){$("#prev_page_button").show()},500);$("#next_page_button:hidden").fadeIn(300)}
function reload(){$(".post h2 a,.readmore a,.postimg a,#nav a,.cate a").click(function(){$("#loading").fadeIn("slow")});$(".readmore").hide();$(".post").hover(function(){$(this).find(".readmore").stop(!0,!0).fadeIn(500)},function(){$(this).find(".readmore").stop(!0,!0).fadeOut(800)});$('a,input[type="submit"],button[type="button"],object').bind("focus",function(){this.blur&&this.blur()})}
function book(){$("#next_page_button").show();pageLayout();$("#prev_page_button").click(function(){$("#prev_page_button").hide(0);prev_page_button_click();return!1});$("#next_page_button").click(function(){$("#next_page_button").hide(0);next_page_button_click();return!1});reload();$("#nav li").hover(function(){$(this).stop().animate({marginTop:"-10px"},250,"swing",function(){$(this).css("overflow","auto")})},function(){$(this).stop().animate({marginTop:"0"},250,"swing",function(){$(this).css("overflow",
"Hidden")})});$("#cup").hover(function(){$("#s").show().focus();$("#searchsubmit").fadeIn()},function(){$("#s,#searchsubmit").hide()})}jQuery(document).ready(function(e){book();e("#loading").fadeOut("slow")});