(function(a){function c(c,b){var l,d,m,n;function u(b){r.start=p?b.pageX:b.pageY;b=parseInt(e.obj.css(j));l=b=="auto"?0:b;a(document).bind("mousemove",q);document.ontouchmove=function(b){a(document).unbind("mousemove");q(b.touches[0])};a(document).bind("mouseup",o);e.obj.bind("mouseup",o);e.obj[0].ontouchend=document.ontouchend=function(b){a(document).unbind("mouseup");e.obj.unbind("mouseup");o(b.touches[0])};return!1}function s(c){f.ratio>=1||(c=a.event.fix(c||window.event),h-=(c.wheelDelta?c.wheelDelta/
120:-c.detail/3)*b.wheel,h=Math.min(f[b.axis]-k[b.axis],Math.max(0,h)),e.obj.css(j,h/m),f.obj.css(j,-h),c.preventDefault())}function o(){a(document).unbind("mousemove",q);a(document).unbind("mouseup",o);e.obj.unbind("mouseup",o);document.ontouchmove=e.obj[0].ontouchend=document.ontouchend=null;return!1}function q(a){f.ratio>=1||(d=Math.min(i[b.axis]-e[b.axis],Math.max(0,l+((p?a.pageX:a.pageY)-r.start))),h=d*m,f.obj.css(j,-h),e.obj.css(j,d));return!1}var k={obj:a(".viewport",c)},f={obj:a(".overview",
c)};n=a(".scrollbar",c);m=void 0;var i={obj:a(".track",n)},e={obj:a(".thumb",n)},p=b.axis=="x",j=p?"left":"top",t=p?"Width":"Height",h;l=0;d=0;var r={};this.update=function(a){k[b.axis]=k.obj[0]["offset"+t];f[b.axis]=f.obj[0]["scroll"+t];f.ratio=k[b.axis]/f[b.axis];n.toggleClass("disable",f.ratio>=1);i[b.axis]=b.size=="auto"?k[b.axis]:b.size;e[b.axis]=Math.min(i[b.axis],Math.max(0,b.sizethumb=="auto"?i[b.axis]*f.ratio:b.sizethumb));m=b.sizethumb=="auto"?f[b.axis]/i[b.axis]:(f[b.axis]-k[b.axis])/(i[b.axis]-
e[b.axis]);h=a=="relative"&&f.ratio<=1?Math.min(f[b.axis]-k[b.axis],Math.max(0,h)):0;h=a=="bottom"&&f.ratio<=1?f[b.axis]-k[b.axis]:isNaN(parseInt(a))?h:parseInt(a);e.obj.css(j,h/m);f.obj.css(j,-h);r.start=e.obj.offset()[j];a=t.toLowerCase();n.css(a,i[b.axis]);i.obj.css(a,i[b.axis]);e.obj.css(a,e[b.axis])};this.update();(function(){e.obj.bind("mousedown",u);e.obj[0].ontouchstart=function(a){a.preventDefault();e.obj.unbind("mousedown");u(a.touches[0]);return!1};i.obj.bind("mouseup",q);if(b.scroll&&
this.addEventListener)c[0].addEventListener("DOMMouseScroll",s,!1),c[0].addEventListener("mousewheel",s,!1);else if(b.scroll)c[0].onmousewheel=s})();return this}a.tiny=a.tiny||{};a.tiny.scrollbar={options:{axis:"y",wheel:40,scroll:!0,size:"auto",sizethumb:"auto"}};a.fn.tinyscrollbar=function(g){g=a.extend({},a.tiny.scrollbar.options,g);this.each(function(){a(this).data("tsb",new c(a(this),g))});return this};a.fn.tinyscrollbar_update=function(c){return a(this).data("tsb").update(c)}})(jQuery);
function abookscroll(){$(".entry,#thecomments").tinyscrollbar()}var commentjs=function(){$("#toolBar").animate({opacity:"show"},400);$.getScript(themeurl+"js/comment.js");$("#comment").unbind("focus",commentjs)},gravatarjs=function(){$.getScript(themeurl+"js/realgravatar.js");$("#email").unbind("focus",gravatarjs)};function getParamsOfShareWindow(a,c){return["toolbar=0,status=0,resizable=1,width="+a+",height="+c+",left=",(screen.width-a)/2,",top=",(screen.height-c)/2].join("")}
function bindShareList(){var a=encodeURIComponent(document.location),c=encodeURIComponent(document.title.substring(0,76)),g=encodeURIComponent("\u7f51\u7ad9\u540d\u79f0"),b=base;jQuery("#twitter-share").click(function(){var b="http://twitter.com/share?url="+a+"&text="+c,d=getParamsOfShareWindow(500,375);window.open(b,"share",d)});jQuery("#fanfou-share").click(function(){var b="http://fanfou.com/sharer?u="+a+"?t="+c,d=getParamsOfShareWindow(600,400);window.open(b,"share",d)});jQuery("#kaixin001-share").click(function(){var b=
"http://www.kaixin001.com/repaste/share.php?rurl="+a+"&rcontent="+a+"&rtitle="+c,d=getParamsOfShareWindow(540,342);window.open(b,"share",d)});jQuery("#renren-share").click(function(){var b="http://share.renren.com/share/buttonshare?link="+a+"&title="+c,d=getParamsOfShareWindow(626,436);window.open(b,"share",d)});jQuery("#douban-share").click(function(){var b="http://www.douban.com/recommend/?url="+a+"&title="+c,d=getParamsOfShareWindow(450,350);window.open(b,"share",d)});jQuery("#sina-share").click(function(){var b=
"http://v.t.sina.com.cn/share/share.php?url="+a+"&title="+c,d=getParamsOfShareWindow(607,523);window.open(b,"share",d)});jQuery("#netease-share").click(function(){var b="http://t.163.com/article/user/checkLogin.do?link="+a+"source="+g+"&info="+c+" "+a,d=getParamsOfShareWindow(642,468);window.open(b,"share",d)});jQuery("#tencent-share").click(function(){var g="http://v.t.qq.com/share/share.php?title="+c+"&url="+a+"&site="+b,d=getParamsOfShareWindow(634,668);window.open(g,"share",d)})}
function abooksingleinit(){$(".post h1 a,#nav a,.cate a").click(function(){$("#loading").fadeIn("slow")});$(".pagecontent,#next_page_button,#prev_page_button").show();$("#next_page_button").html()==""&&$("#next_page_button").hide();$("#prev_page_button").html()==""&&$("#prev_page_button").hide();$('a,input[type="submit"],button[type="button"],object').bind("focus",function(){this.blur&&this.blur()});$(".tg_t").click(function(){$(this).next(".tg_c").slideToggle(400);$(".entry").tinyscrollbar_update("relative")});
$(".entry img").each(function(){var a;a=$(window).width()>=1280&&$(window).height()>=799?460:360;var c=0,g=$(this).width(),b=$(this).height();g>a&&(c=a/g,$(this).css("width",a),b*=c,$(this).css("height",b));b>560&&(c=560/b,$(this).css("height",560),g*=c,$(this).css("width",g))});bindShareList();$("#comment").bind("focus",commentjs);$("#email").bind("focus",gravatarjs);$("#edit_profile").toggle(function(){$("#welcome_msg").slideUp(200);$("#guest_info").slideDown(200);$("#edit_profile").html(" (\u6539\u597d\u4e86\u5427~)");
return!1},function(){$("#welcome_msg").slideDown(200);$("#guest_info").slideUp(200);$("#edit_profile").html(" (\u518d\u6539\u4e00\u6b21\uff1f)");return!1});$(".entry").find("a:has(img)").length&&$.getScript(themeurl+"js/slimbox.js",function(){$(".entry a[href]").filter(function(){return/\.(jpg|png|gif)$/i.test(this.href)}).slimbox({},null,function(a){return this==a||this.parentNode&&this.parentNode==a.parentNode})});$(".entry a:has(img)").each(function(){var a;a=$(this).attr("href").match(/(jpg|gif|jpeg|png|tif)/)?
"zoom_image":"";var c=$(this).contents("img");c.length>0&&(c.wrap("<span class="+a+"></span>"),c.parent().css({display:"inline-block"}))});$(".entry a img").hover(function(){$(this).stop().animate({opacity:0.5},400)},function(){$(this).stop().animate({opacity:1},400)});$("#related_area img").hover(function(){$(this).fadeTo("fast",0.7)},function(){$(this).fadeTo("fast",1)});abookscroll();$("#comment_header li").click(function(){$(this).addClass("comment_switch_active").siblings().removeClass();$("#comment_content > div").hide(400).eq($("#comment_header li").index(this)).fadeIn(500);
$("#thecomments").tinyscrollbar_update();return!1});$(".com_num").click(function(){$("#comment_switch").addClass("comment_switch_active").siblings().removeClass();$("#comment_content > div").hide(400).eq(1).fadeIn(500);$("#thecomments").tinyscrollbar_update();$("#comment_parent").attr("value","0");$("#comment").attr("value","").focus();return!1});commentajax();comment_pager();singleajax();$("#loading").fadeOut("slow")}
function commentajax(){$(".fn a").attr({target:"_blank"});$(".comment .avatar").load(function(){$(this).wrap(function(){return'<span class="'+$(this).attr("class")+'" style="background:url('+$(this).attr("src")+") no-repeat center center; width: "+$(this).width()+"px; height: "+$(this).height()+'px;" />'});$(this).css("opacity","0")});$(".reply").hide(0);$(".commnetdiv").hover(function(){$(this).find(".reply").stop(!0,!0).fadeIn(300)},function(){$(this).find(".reply").stop(!0,!0).fadeOut(300)});$(".comment-reply-link").click(function(){var a=
$(this).parent().parent().attr("id"),c=$(this).attr("id").split("reply-")[1].split("-")[0],g=$(this).attr("id").split("reply-")[1].split("-")[1],b='"#'+a+'"',l=$(this).parent().parent().find("cite:first").text();$("#commento").html("<a href="+b+">@"+l+"</a>,");$("#add_comment").addClass("comment_switch_active").siblings().removeClass();$("#comment_content > div").hide(400).eq(0).show(500);$("#comment").focus();$("#comment_post_ID").attr("value",c);$("#comment_parent").attr("value",g);c=$("#"+a).html();
$("#ajaxpre").html("").html('<li id="ajaxtempview" class="commentlist comment" style="background:#ddd"><div>'+c+"</div></li>").show();$("#cancel-comment-reply-link").show();$("#cancel-comment-reply-link").unbind("click").bind("click",function(){$("#comment_switch").addClass("comment_switch_active").siblings().removeClass();$("#respond_area").hide(400);$("#comment_area").show(500);$("#comment").attr("value","");$("#commento").html("");$("#comment_parent").attr("value","0");$("#cancel-comment-reply-link,#ajaxpre").hide();
$("#"+a).focus();return!1});return!1})}
function comment_pager(){$("#comment_pager a").click(function(){var a=$(this).attr("href").split(/(\?|&)action=AjaxCommentsPage.*$/)[0],c=1;/comment-page-/i.test(a)?c=a.split(/comment-page-/i)[1].split(/(\/|#|&).*$/)[0]:/cpage=/i.test(a)&&(c=a.split(/cpage=/)[1].split(/(\/|#|&).*$/)[0]);var g=$("#comment_post_ID").attr("value"),b=a.split(/#.*$/)[0];b+=/\?/i.test(a)?"&":"?";b+="action=AjaxCommentsPage&post="+g+"&page="+c;$.ajax({url:b,type:"GET",beforeSend:function(){$("#comment_pager").hide();$("#thecomments .overview").html('<div id="com_loading">\u6b63\u5728\u52aa\u529b\u8bfb\u53d6\u4e2d......</div>');
$("#thecomments").tinyscrollbar_update()},error:function(a){alert(a.responseText)},success:function(a){a=a.split("<\!--Abook-AJAX-COMMENT-PAGE--\>");$("#thecomments .overview").html(a[0]);$("#comment_pager").html(a[1]);$("#thecomments").tinyscrollbar_update();commentajax();comment_pager();$("#thecomments .overview,#comment_pager").show()}});return!1})}
function singleajax(){$("#next_page_button,#prev_page_button").click(function(){var a=$(this).children().attr("href");a+=/\?/i.test(a)?"&":"?";a+="act=singlePage";$.ajax({url:a,dataType:"html",contentType:"application/json; charset=utf-8",cache:!0,beforeSend:function(){$("#prev_page_button,#next_page_button").fadeOut(0);$("#loading").show()},success:function(a){$("#main").empty().html(a);abooksingleinit()}});return!1})}
jQuery(document).ready(function(a){abooksingleinit();a("#nav li").hover(function(){a(this).stop().animate({marginTop:"-10px"},250,"swing",function(){a(this).css("overflow","auto")})},function(){a(this).stop().animate({marginTop:"0"},250,"swing",function(){a(this).css("overflow","Hidden")})});a("#cup").hover(function(){a("#s").show().focus();a("#searchsubmit").fadeIn()},function(){a("#s,#searchsubmit").hide()})});